### PR TITLE
Added/updated scraper recipes and have better output for running reports

### PR DESCRIPTION
**Pull request by iwasrobbed**
We still need to go through and add `test_contains` and optionally `test_contains_image` for all non-subdomain sitespec files, but this is a good start.

I updated the `runreport.py` file to have better output so we can more easily see what is passing, failing, throwing exceptions, or having warnings. I'm not very good w/ Python so please feel free to give constructive criticism for how anything can be improved/simplified.

These reports take a long time to run and are pretty unstable/brittle since they can easily break if the HTML structure of any recipe page changes, so I think it's best to not have them attached to the py.test suite. We can have a secondary script/server that runs a daily check and reports any issues.

### CODE REVIEW

**Comment by iwasrobbed** [comment]
@bigblind I haven't worked much with testing & Python. If you have a moment, would you mind helping me with this issue after merging the cache branch changes?

```shell
(saulify)Robs-Air:saulify rob$ foreman run python runreport.py

-----------------------------
Running 950 sitespec tests...
-----------------------------

Traceback (most recent call last):
  File "runreport.py", line 140, in <module>
    report = test_case.run()
  File "/Users/rob/saulify/saulify/testcase.py", line 32, in run
    output = clean_url(self.url)
  File "/Users/rob/saulify/saulify/cache.py", line 111, in wrapper
    value = cache.get(key)
  File "/Users/rob/saulify/saulify/cache.py", line 55, in get
    value = cache.get(key)
  File "/Users/rob/saulify/saulify/cache.py", line 28, in get
    self._ensure_cache_exists()
  File "/Users/rob/saulify/saulify/cache.py", line 25, in _ensure_cache_exists
    flask.g._cache = {}
  File "/Users/rob/.virtualenvs/saulify/lib/python2.7/site-packages/werkzeug/local.py", line 355, in <lambda>
    __setattr__ = lambda x, n, v: setattr(x._get_current_object(), n, v)
  File "/Users/rob/.virtualenvs/saulify/lib/python2.7/site-packages/werkzeug/local.py", line 297, in _get_current_object
    return self.__local()
  File "/Users/rob/.virtualenvs/saulify/lib/python2.7/site-packages/flask/globals.py", line 27, in _lookup_app_object
    raise RuntimeError('working outside of application context')
RuntimeError: working outside of application context
```

**Comment by bigblind** [comment]
@iwasrobbed This occurs because flask.g is only availablee within the [application context](http://flask.pocoo.org/docs/0.10/appcontext/). This should probably be resolved when you ask for the `app` fixture in your tests.

**Comment by iwasrobbed** [comment]
Thanks @bigblind, that fixed things up. While running the scraper recipe tests, I'm now getting a data insert error on the db from the Article authors. It's specifying a field with a limit set to 120 is being exceeded, so we should probably increase the size of the `authors` field for articles with a lot of collaboration. I'm more familiar with Ruby on Rails migrations, but how would we handle migrating this on Flask/Python?

The Newspaper scraper is also scraping too many authors, like: `Home Fires, Stanley Fish, All Contributors, Richard Conniff, The Conversation, Errol Morris, The Great Divide, Measure For Measure`

Full exception output here: https://gist.github.com/iwasrobbed/072177c1c7ed46c2f471

**Comment by bigblind** [comment]
@iwasrobbed I'll take a closer look later tonight for migrations. This is my first project where I've used postgres, and sqlalchemy in general. [Formspree](http:/assembly.com/formspree) uses the flask-migrate plugin, we might want to take a look at that.

**Pull request closed without merging**
